[package]
name = "chunk-json-lite"
version = "0.1.0"
authors = ["Clément Renault <clement@meilisearch.com>"]
edition = "2018"

[dependencies]
count-write = "0.1.0"
human-size = "0.4.0"
json = "0.12.0"
main_error = "0.1.0"
